#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""{{.Name}} - {{.Description}}


Copyright (C) {{.Year}} {{.Author}}

"""

import argparse
import sys
import os

__author__ = "{{.Author}}"
__copyright__ = "{{.Copyright}}"
__email__ = "{{.MailAddress}}"
__license__ = "{{.License}}"
__version__ = "1.0.1"


def parse_args(args):
    """
    Parse command line parameters

    :param args: command line parameters as list of strings
    :return: command line parameters as :obj:`argparse.Namespace`
    """
    retv = dict()
    parser = argparse.ArgumentParser()

    parser.add_argument(
        '--version',
        action='version',
        version='{{.Name}} {ver}'.format(ver=__version__))

    parser.add_argument('rest', nargs='*')


    opts = vars(parser.parse_args(args))

    for keyn, keyv in opts.items():
        if keyv is not None:
            retv[keyn] = keyv

    return retv


def main(args):
    args = parse_args(args)


if __name__ == "__main__":
    main(sys.argv[1:])
